site_name: lammps-tutorial

theme:
  name: material
  language: zh-Hant
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css