site_name: lammps-tutorial
repo_name: lammpscn
repo_url: https://github.com/Roy-Kid/lammpscn2

theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: docs/overrides

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - navigation.indexes
    - navigation.expand
    - toc.follow
    - toc.integrate
    - content.action.edit

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Roy-Kid/lammpscn2

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - mkdocs-jupyter

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      title: On this page
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2019-2023 Roy Kid